import os
import re
import subprocess
from dataclasses import dataclass

from jobflow import Maker, job, Response

from atomate2.dmax.schemas.task import DmaxLammpsInputDocument, DmaxLammpsRunDocument


@dataclass
class LammpsSlurmRunMaker(Maker):
    """
    Maker to submit a LAMMPS SLURM run generated by StructureEquilInputMaker.

    It submits the SLURM script and returns the SLURM job ID.
    """
    name: str = "lammps_slurm_run"

    @job(output_schema=DmaxLammpsRunDocument)
    def make(self, input_doc: DmaxLammpsInputDocument) -> Response:
        # Change to the input directory
        cwd = os.getcwd()
        os.chdir(input_doc.input_dir)
        try:
            # Submit the SLURM job
            out = subprocess.check_output(["sbatch", input_doc.slurm_file], stderr=subprocess.STDOUT).decode()
        finally:
            os.chdir(cwd)
        # Parse the SLURM job ID
        m = re.search(r"Submitted batch job (\d+)", out)
        if not m:
            raise RuntimeError(f"Failed to submit SLURM script: {out}")
        job_id = m.group(1)
        # determine restart path
        restart_path = os.path.join(input_doc.input_dir, 'restart.equil')
        return Response(output=DmaxLammpsRunDocument(job_id=job_id, restart_file=restart_path))


@dataclass
class LammpsLocalRunMaker(Maker):
    """
    Maker to run the SLURM script locally via bash instead of submitting to SLURM.
    """
    name: str = "lammps_local_run"
    # whether to use GPU-accelerated LAMMPS
    use_gpu: bool = False
    # number of GPUs to request
    gpu_count: int = 1

    @job(output_schema=DmaxLammpsRunDocument)
    def make(self, input_doc: DmaxLammpsInputDocument) -> Response:
        # Change to the input directory and run LAMMPS directly
        cwd = os.getcwd()
        os.chdir(input_doc.input_dir)
        try:
            # run LAMMPS binary with input script and log, choose GPU if requested
            if self.use_gpu:
                lmp_bin = os.environ.get('LAMMPS_BINARY_GPU', 'lmp_gpu')
                cmd = [lmp_bin, '-sf', 'gpu', '-pk', 'gpu', str(self.gpu_count), '-in', input_doc.input_file, '-log', 'lammps.log']
            else:
                lmp_bin = os.environ.get('LAMMPS_BINARY', 'lmp_mpi')  # default to mpi binary
                cmd = [lmp_bin, '-in', input_doc.input_file, '-log', 'lammps.log']
            subprocess.check_call(cmd)
        finally:
            os.chdir(cwd)
        # Use 'local' as job_id and capture restart file path
        restart_path = os.path.join(input_doc.input_dir, 'restart.equil')
        return Response(output=DmaxLammpsRunDocument(job_id="local", restart_file=restart_path))
