"""
Pydantic Task Documents for DMAx jobs.
"""
from pydantic import BaseModel, Field
from typing import Optional, Any

class DmaxStructureTaskDocument(BaseModel):
    """
    Task document for polymer structure generation.
    """
    packmol_pdb: Optional[str] = Field(
        None, description="Contents of the packmol PDB file"
    )
    polymer_pdb: Optional[str] = Field(
        None, description="Contents of the generated polymer PDB file"
    )
    builder_wrapper: Optional[Any] = Field(
        None, description="Serialized PSPBuilderWrapper for reuse"
    )

class DmaxForceFieldTaskDocument(BaseModel):
    """
    Task document for forcefield parametrization.
    """
    data_file: str = Field(
        ..., description="Path or name of the generated LAMMPS data file"
    )
    lammps_data: Optional[str] = Field(
        None, description="Contents of the generated LAMMPS data file"
    )
    forcefield_type: str = Field(
        ..., description="Type of forcefield used ('opls' or 'gaff2')"
    )

class DmaxDataGenerationFlowDocument(BaseModel):
    """
    Document for the complete DMAx data generation flow.
    """
    packmol_pdb: Optional[Any] = Field(
        None, description="Reference or contents of the packmol PDB file"
    )
    polymer_pdb: Optional[Any] = Field(
        None, description="Reference or contents of the generated polymer PDB file"
    )
    lammps_data: Optional[Any] = Field(
        None, description="Reference or contents of the generated LAMMPS data file"
    )

class DmaxLammpsInputDocument(BaseModel):
    """
    Task document for generated LAMMPS input files.
    """
    input_dir: str = Field(
        ..., description="Directory containing generated LAMMPS input and slurm files"
    )
    data_file: str = Field(
        ..., description="Filename of the LAMMPS data file in the input directory"
    )
    input_file: str = Field(
        ..., description="Filename of the LAMMPS input script generated from template"
    )
    slurm_file: str = Field(
        ..., description="Filename of the SLURM run script in the input directory"
    )

class DmaxLammpsRunDocument(BaseModel):
    """
    Task document for a submitted LAMMPS SLURM run.
    """
    job_id: str = Field(
        ..., description="SLURM job ID for the LAMMPS run or 'local'"
    )
    restart_file: Optional[str] = Field(
        None, description="Path to the restart.equil file generated by LAMMPS"
    )

class DmaxStructureEquilibrationFlowDocument(BaseModel):
    """
    Document for the complete structure equilibration flow: structure, parametrization,
    input generation, run, and output artifacts.
    """
    packmol_pdb: Optional[Any] = Field(
        None, description="Contents of the packmol PDB file for the polymer structure"
    )
    polymer_pdb: Optional[Any] = Field(
        None, description="Contents of the generated polymer PDB file"
    )
    lammps_data: Optional[Any] = Field(
        None, description="Contents of the LAMMPS data file"
    )
    lammps_input: Optional[Any] = Field(
        None, description="Filename of the LAMMPS input script (OutputReference)"
    )
    slurm_file: Optional[Any] = Field(
        None, description="Filename of the SLURM run script (OutputReference)"
    )
    job_id: Optional[Any] = Field(
        None, description="SLURM job ID for the LAMMPS run or 'local' (OutputReference)"
    )
    restart_file: Optional[Any] = Field(
        None, description="Path to the restart.equil file generated by LAMMPS (OutputReference)"
    )

class DmaxStructureEquilParserDocument(BaseModel):
    """
    Task document for parsing structure equilibration outputs: thermo, MSD, VACF, RDF, and restart.
    """
    restart_file: Optional[Any] = Field(
        None, description="Path to the restart.equil file used/retrieved"
    )
    thermo_csv: Optional[str] = Field(
        None, description="Path to the CSV file containing thermo data"
    )
    thermo_plot: Optional[str] = Field(
        None, description="Path to the time vs thermo plot"
    )
    msd_plot: Optional[str] = Field(
        None, description="Path to the mean squared displacement plot"
    )
    vacf_plot: Optional[str] = Field(
        None, description="Path to the velocity autocorrelation function plot"
    )
    rdf_plot: Optional[str] = Field(
        None, description="Path to the radial distribution function plot"
    )

class DmaxDmaParserDocument(BaseModel):
    "Task document for parsing DMA outputs: moduli, phase, and plots."
    storage_modulus: float = Field(..., description="Storage modulus in MPa")
    loss_modulus: float = Field(..., description="Loss modulus in MPa")
    tan_delta: Optional[float] = Field(None, description="Loss tangent")
    elastic_modulus: float = Field(..., description="Elastic modulus (slope) in MPa")
    poisson_ratio: float = Field(..., description="Poisson's ratio")
    phase_angle_rad: float = Field(..., description="Phase angle in radians")
    phase_angle_deg: float = Field(..., description="Phase angle in degrees")
    fit_r2: float = Field(..., description="R² of sinusoidal fit")
    fit_rmse: float = Field(..., description="RMSE of sinusoidal fit in MPa")
    amplitude: float = Field(..., description="Amplitude of fitting curve in MPa")
    pressure_plot: str = Field(..., description="Path to pressure vs time fit plot")
    stress_strain_plot: str = Field(..., description="Path to stress-strain curve plot")

class DmaxDmaFlowDocument(BaseModel):
    "Flow document for complete DMA run: input, run, parser outputs."
    lammps_input: Optional[Any] = Field(None, description="Reference to DMA input task output")
    slurm_file: Optional[Any] = Field(None, description="SLURM script file (OutputReference)")
    job_id: Optional[Any] = Field(None, description="SLURM job ID or 'local' (OutputReference)")
    restart_file: Optional[Any] = Field(None, description="Restart file path (OutputReference)")
    parser_output: Optional[Any] = Field(None, description="Parsed DMA results (OutputReference)")
